/*
 * Copyright (C) 2026 Darkmine Pty Ltd
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { alphaBetaToDipAzimuth } from '../src/data/structural.js';

const testDir = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.resolve(testDir, '../../../../test/data/structural_reference.json');
const hasFixture = existsSync(FIXTURE_PATH);

/** Smallest angular distance between two azimuths, handling the 0/360 wrap. */
function azimuthDistance(first, second) {
  const diff = Math.abs(first - second) % 360;
  return Math.min(diff, 360 - diff);
}

describe('alphaBetaToDipAzimuth — sanity anchors', () => {
  it('alpha=90 on an inclined hole returns the plane perpendicular to the core axis', () => {
    // Hole drilled toward north plunging 45°: the perpendicular plane dips 45°
    // back toward the drill direction's antipode (south), for any beta.
    for (const beta of [0, 90, 180, 270]) {
      const { dip, dipDirection } = alphaBetaToDipAzimuth(-45, 0, 90, beta);
      expect(dip).toBeCloseTo(45, 9);
      expect(azimuthDistance(dipDirection, 180)).toBeLessThan(1e-9);
    }
  });

  it('vertical hole with alpha=90 returns a horizontal plane (dip 0, direction 0)', () => {
    const { dip, dipDirection } = alphaBetaToDipAzimuth(-90, 0, 90, 45);
    expect(dip).toBeCloseTo(0, 9);
    expect(dipDirection).toBe(0);
  });

  it('vertical hole falls back to the north reference: alpha=30, beta=90 → dip 60 east', () => {
    const { dip, dipDirection } = alphaBetaToDipAzimuth(-90, 0, 30, 90);
    expect(dip).toBeCloseTo(60, 9);
    expect(azimuthDistance(dipDirection, 90)).toBeLessThan(1e-9);
  });

  it('accepts arrays and broadcasts scalar hole orientation across them', () => {
    const { dip, dipDirection } = alphaBetaToDipAzimuth(-45, 0, [90, 45], [0, 180]);
    expect(dip).toHaveLength(2);
    expect(dipDirection).toHaveLength(2);
    expect(dip[0]).toBeCloseTo(45, 9);
    expect(azimuthDistance(dipDirection[0], 180)).toBeLessThan(1e-9);
    // alpha=45, beta=180 (apex up-hole): the plane flattens out to horizontal.
    expect(dip[1]).toBeCloseTo(0, 9);
    expect(dipDirection[1]).toBe(0);
  });
});

if (!hasFixture) {
  console.log(
    `structural_reference.json not found at ${FIXTURE_PATH} — skipping the `
    + 'cross-language reference assertions (the fixture is generated by the '
    + 'Python implementation and will exist before merge).'
  );
}

describe.skipIf(!hasFixture)('alphaBetaToDipAzimuth — Python reference fixture', () => {
  it('matches every reference case to 1e-6', () => {
    const cases = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8'));
    expect(cases.length).toBeGreaterThan(0);
    for (const referenceCase of cases) {
      const { dip, dipDirection } = alphaBetaToDipAzimuth(
        referenceCase.hole_dip,
        referenceCase.hole_azimuth,
        referenceCase.alpha,
        referenceCase.beta
      );
      expect(
        Math.abs(dip - referenceCase.expected_dip),
        `dip mismatch for ${JSON.stringify(referenceCase)} (got ${dip})`
      ).toBeLessThan(1e-6);
      expect(
        azimuthDistance(dipDirection, referenceCase.expected_dip_direction),
        `dip_direction mismatch for ${JSON.stringify(referenceCase)} (got ${dipDirection})`
      ).toBeLessThan(1e-6);
    }
  });
});
